import Image from 'next/image'
import Favicon from '/public/images/Metadata/logo.ico';
import CamisaPersonalizada from '../../../public/images/camisa-personalizada.webp'
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Meu Mundo Personalizado - Camisa Preta',
    description: 'Generated by create next app',
    icons: [{ rel: 'icon', url: Favicon.src }],
  };

export default function Page(){
    return(
        <>
            <div className='flex justify-center'>
                <div className='mt-20 w-max h-max rounded-xl shadow-lg shadow-gray-300 md:shadow-xl md:shadow-gray-300'>
                    <Image
                    src={CamisaPersonalizada}
                    alt="Wallpaper do site"
                    />
                    <p>Camiseta Personalizada - Envie sua arte</p>
                </div>
            </div>
        </>
        
    )
}