import './globals.css'
import Image from 'next/image'
import wallpaper from '../../public/images/Wallpaper.png'

import Favicon from '/public/images/Metadata/logo.ico';
import { Metadata } from 'next';

import qualificacao from '../../public/images/qualificacao.svg'
import CoracaoVermelho from '../../public/images/corao-like.svg'
import CamisaPersonalizada from '../../public/images/camisa-personalizada.webp'
import CamisaVermelha from '../../public/images/camisa-personalizada-vermelha.webp'
import CamisaCinza from '../../public/images/camisa-personalizada-cinza.webp'
import CamisaBranca from '../../public/images/camisa-personalizada-white.webp'
import CamisaBrancaZoom from '../../public/images/camisa-personalizada-white-zoom.webp'

import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Meu Mundo Personalizado',
  description: 'Generated by create next app',
  icons: [{ rel: 'icon', url: Favicon.src }],
};


// function productHover(){
    
// }


export default function Page() {
    return (
      <>
        <div>
          <Image
              src={wallpaper}
              alt="Wallpaper do site"
            />
        </div>

        <div className="grid justify-center">
          <h2 className="font-bold font-['Poppins'] text-3xl">Ofertas especiais</h2>
          <p className="font-['Poppins'] text-xl">Os melhores preços</p>
        </div>

        <div className="flex justify-center ml-32 mr-32">
          <div className="grid sm:grid-cols-2 md:grid-col-3 xl:grid-cols-4 gap-12 justify-items-center mt-5 w-4/4">
            <Link href='/camisa-preta' className='hover: hover:bg-violet-600'>
              <div className="w-72 mb-10 h-max rounded-xl shadow-lg shadow-gray-300 md:shadow-xl md:shadow-gray-300 flex flex-col">
                <Image className="h-max self-center" src={CamisaPersonalizada} alt="Produto 1"/>
                <h1 className="ml-3 mt-2 font-bold font-['Poppins'] text-sm">Camiseta Personalizada - Envie sua arte</h1>
                <Image className="ml-4 w-14  h-max font- ['Poppins'] text-md" src={qualificacao} alt="qualificacao do produto"/>
                  <div className="flex justify-between mr-10">
                    <h2 className="ml-3 mt-2">R$ 3.599<span className="text-xs">,99</span></h2>
                    <button className="">
                      <Image className="w-8" src={CoracaoVermelho} alt="Cutiu"/>
                    </button> 
                  </div>
                  <span className="ml-3 text-xs font-['Poppins'] text-current">10x de R$250</span>
              </div>
            </Link>
            <Link href='/camisa-vermelha'>
              <div className="w-72 mb-10 h-max rounded-xl shadow-lg shadow-gray-300 md:shadow-xl md:shadow-gray-300 flex flex-col">
                <Image className="h-max self-center" src={CamisaVermelha} alt="Produto 2"/>
                <h1 className="ml-3 mt-2 font-bold font-['Poppins'] text-sm">Camiseta Personalizada - Envie sua arte</h1>
                <Image className="ml-4 w-14  h-max font- ['Poppins'] text-md" src={qualificacao} alt="qualificacao do produto"/>
                <h2 className="ml-3 mt-2">R$ 3.599<span className="text-xs">,99</span></h2> 
                <span className="ml-3 text-xs font-['Poppins'] text-current">10x de R$250</span>
              </div>
            </Link>
            <Link href='/camisa-cinza'>
              <div className="w-72 mb-10 h-max rounded-xl shadow-lg shadow-gray-300 md:shadow-xl md:shadow-gray-300 flex flex-col">
                <Image className="h-max self-center" src={CamisaCinza} alt="Produto 1"/>
                <h1 className="ml-3 mt-2 font-bold font-['Poppins'] text-sm">Camiseta Personalizada - Envie sua arte</h1>
                <Image className="ml-4 w-14  h-max font- ['Poppins'] text-md" src={qualificacao} alt="qualificacao do produto"/>
                <h2 className="ml-3 mt-2">R$ 3.599<span className="text-xs">,99</span></h2> 
                <span className="ml-3 text-xs font-['Poppins'] text-current">10x de R$250</span>
              </div>
            </Link>
            <Link href='/camisa-branca'>
              <div className="w-72 mb-10 h-max rounded-xl shadow-lg shadow-gray-300 md:shadow-xl md:shadow-gray-300 flex flex-col">
                <Image className="h-max self-center" src={CamisaBranca} alt="Produto 1"/>
                <h1 className="ml-3 mt-2 font-bold font-['Poppins'] text-sm">Camiseta Personalizada - Envie sua arte</h1>
                <Image className="ml-4 w-14  h-max font- ['Poppins'] text-md" src={qualificacao} alt="qualificacao do produto"/>
                <h2 className="ml-3 mt-2">R$ 3.599<span className="text-xs">,99</span></h2> 
                <span className="ml-3 text-xs font-['Poppins'] text-current">10x de R$250</span>
              </div>
            </Link>
          </div>
        </div>
    </>
    )
  }